<a href="https://colab.research.google.com/github/joseph444/ml-algos/blob/master/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Linear Regression Using Closed Form Solution and gradient Descent formula for accuracy </h1>


In [ ]:
import numpy as np
import math as mt

In [ ]:
#class linear regression
class LinearRegression:

    def __init__(self,epoc=80,lr=0.01):
        #lr is the learning rate 
        self.lr=lr
        #no of times gradient Desent will be working
        self.epoc=epoc
        pass
    def polyFit(self,X,Y,n):
        '''
          X: numpy array
          Y: nump array
          n: highest power
        '''
        self.X=np.ones((X.shape[0],1))
        for i in range(1,n+1):
            self.X=np.hstack((self.X,X**i))
        self.Y=np.reshape(Y,(Y.shape[0],1))
        self.Xt=np.transpose(self.X)
        self._X=X
        self._regression()
        self.n=n

    def fit(self,X,Y):
        '''
          X: numpy array
          Y: nump array
         
        '''
        ones=np.ones((X.shape[0],1))
        self.X=np.hstack((ones,X))
        self.Y=np.reshape(Y,(Y.shape[0],1))
        self.Xt=np.transpose(self.X)
        self._X=X
        self._regression()
        pass
    def _regression(self):
        '''
          this function uses the closed form solution of linear regression to calculate the regression
        '''
        w=np.dot(self.Xt,self.X)
        p1=np.linalg.inv(w)
        
        p2=np.dot(np.transpose(self.X),self.Y)
       
        self.omega=np.dot(p1,p2)#this is the regression coefficient
        
        self._train()
        pass
    def gradient(self):
        ''' 
          it calculates the gradient and modifies the omega accoring to it
        '''
        P=self.predictY()-self.Y
        Q=np.transpose(P)
        Grad=np.dot(Q,P)
        #print(Grad.shape)
        Grad=(self.lr/self.Y.shape[0])*Grad
        self.omega=self.omega-Grad
    def predictY(self):
        '''
          returns the predicted value of training data
        '''
        return np.dot(self.X,self.omega)
        pass
    def RMSE(self):
        """
          ROOT MEAN SQUARE to calculate the root mean square of the predicted value
        """
        M=(self.predictY()-self.Y)**2
        x=np.mean(M)
        return mt.sqrt(x)
    def _train(self):
        """
          this runs the loop for running the epoc loop and modifying the gradient
        """

        for i in range(self.epoc):
            print(self.omega)
            self.gradient()

        pass
    def PolyPredict(self,X):
        """
          Predict function for the poly Regression returns Predicted Value from X
        """
        _X=np.ones((X.shape[0],1))
        for i in range(1,self.n+1):
            _X=np.hstack((_X,_X**i))
        return np.dot(_X,self.omega)
    def predict(self,X):
        """
          Predict function for the Regression returns Predicted Value from X
        """
        ones=np.ones((X.shape[0],1))
        _X=np.hstack((ones,X))
        return np.dot(_X,self.omega)



In [ ]:
linearModel=LinearRegression(epoc=1)
m=np.linspace(0,10,1000)
y=np.linspace(0,20,1000)
z=np.linspace(0,100,1000)
X=np.array([m,y,z])
X=np.reshape(X,(m.shape[0],3))
Y=np.linspace(0,2,1000)
Y=np.reshape(Y,(Y.shape[0],1))
linearModel.fit(X,Y)
linearModel.omega



[[ 0.61402429]
 [-0.04996754]
 [ 0.07205904]
 [-0.00435215]]
(1, 1)


array([[ 0.61289959],
       [-0.05109224],
       [ 0.07093435],
       [-0.00547685]])

In [ ]:
m=np.linspace(0,10,100)
y=np.linspace(0,20,100)
z=np.linspace(0,100,100)
X=np.array([m,y,z])
X=np.reshape(X,(m.shape[0],3))
linearModel.predict(X)

array([[0.61895824],
       [0.62331135],
       [0.62766446],
       [0.63201757],
       [0.63637068],
       [0.64072378],
       [0.64507689],
       [0.64943   ],
       [0.65378311],
       [0.65813622],
       [0.66248933],
       [0.66684244],
       [0.67119554],
       [0.67554865],
       [0.67990176],
       [0.68425487],
       [0.68860798],
       [0.69296109],
       [0.69731419],
       [0.7016673 ],
       [0.70602041],
       [0.71037352],
       [0.71472663],
       [0.71907974],
       [0.72343285],
       [0.72778595],
       [0.73213906],
       [0.73649217],
       [0.74084528],
       [0.74519839],
       [0.7495515 ],
       [0.7539046 ],
       [0.75825771],
       [0.10087076],
       [0.63082104],
       [0.63952726],
       [0.64823347],
       [0.65693969],
       [0.66564591],
       [0.67435212],
       [0.68305834],
       [0.69176456],
       [0.70047077],
       [0.70917699],
       [0.71788321],
       [0.72658942],
       [0.73529564],
       [0.744

In [ ]:
ypred

array([[-8.88178420e-16],
       [ 2.02020202e-02],
       [ 4.04040404e-02],
       [ 6.06060606e-02],
       [ 8.08080808e-02],
       [ 1.01010101e-01],
       [ 1.21212121e-01],
       [ 1.41414141e-01],
       [ 1.61616162e-01],
       [ 1.81818182e-01],
       [ 2.02020202e-01],
       [ 2.22222222e-01],
       [ 2.42424242e-01],
       [ 2.62626263e-01],
       [ 2.82828283e-01],
       [ 3.03030303e-01],
       [ 3.23232323e-01],
       [ 3.43434343e-01],
       [ 3.63636364e-01],
       [ 3.83838384e-01],
       [ 4.04040404e-01],
       [ 4.24242424e-01],
       [ 4.44444444e-01],
       [ 4.64646465e-01],
       [ 4.84848485e-01],
       [ 5.05050505e-01],
       [ 5.25252525e-01],
       [ 5.45454545e-01],
       [ 5.65656566e-01],
       [ 5.85858586e-01],
       [ 6.06060606e-01],
       [ 6.26262626e-01],
       [ 6.46464646e-01],
       [ 6.66666667e-01],
       [ 6.86868687e-01],
       [ 7.07070707e-01],
       [ 7.27272727e-01],
       [ 7.47474747e-01],
       [ 7.6